### ISSUE TITLE
Here is a screen shot so you can help me fix my problem #10184

### ISSUE THREAD

**Issue by 236286** [francoispluchino/composer-asset-plugin#163] opened 2015-11-18 11:44 UTC
I did these steps:
1) curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
2) composer global require "fxp/composer-asset-plugin:~1.1.0"
3) composer create-project --prefer-dist yiisoft/yii2-app-basic basic

After that, I had a problem

Here is a screen shot so you can see the problem I am having:

![2015-11-18-180428_1280x1024_scrot](https://cloud.githubusercontent.com/assets/12777801/11240324/f40708ac-8e1b-11e5-84d3-a9f603f217db.png)

Can you help me fix my problem?

**Comment by samdark** [comment] 2015-11-18 12:02
https://github.com/francoispluchino/composer-asset-plugin/pull/158

**Comment by githubjeka** [comment] 2015-11-18 12:13
failed to reproduce

![image](https://cloud.githubusercontent.com/assets/874234/11240853/e51f0e62-8e06-11e5-8afd-176c478de599.png)

**Comment by francoispluchino** [comment] 2015-11-18 13:06
@236286 Clean your composer caches. Maybe it solves your problem.

**Comment by githubjeka** [comment] 2015-11-18 13:08
He tried delete all by
`sudo find / -name "composer*"`

**Comment by githubjeka** [comment] 2015-11-18 13:19
Perhaps his problem relates with the network, because another computer on the same subnet have the same problem.

**Comment by 236286** [comment] 2015-11-19 05:51
my internet is working

**Comment by githubjeka** [comment] 2015-11-19 06:45
Bower cannot get package also
![https://files.gitter.im/236286/xGuP/2015-11-19-133341_1366x768_scrot.png](https://files.gitter.im/236286/xGuP/2015-11-19-133341_1366x768_scrot.png)

# REL https://github.com/bower/bower/issues/1385

**Comment by francoispluchino** [comment] 2015-11-19 07:22
@githubjeka Ok, this issue can be closed now.

**Comment by githubjeka** [comment] 2015-11-19 07:24
Yes, it is local problem with DNS....

**Comment by samdark** [comment] 2015-11-19 08:46
Close the issue then.

**Closed** 2016-02-28 16:44 UTC
Labels: support
